language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  # print the version for logging
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed tuyojr/udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user tuyojr/udagram-api-user
  - docker build -t reverseproxy ./reverseproxy
  - docker tag reverseproxy tuyojr/reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend tuyojr/udagram-frontend

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tuyojr/udagram-api-feed:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tuyojr/udagram-api-user:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tuyojr/reverseproxy:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tuyojr/udagram-frontend:v1
